### PR TITLE
Cygwin support

### PR DESCRIPTION
**Pull request by crd477**
I recently went through the process of packaging passwdqc for Cygwin.  You can see my changes against the v2.0.2 release tarball here: https://github.com/crd477/passwdqc-cygport

This PR contains a forward port of my changes to the Makefile in `main`. If you're willing to merge this, it should make the effort of repackaging any future versions a lot easier. Thanks!

### CODE REVIEW

**Comment by solardiz** [comment]
@ldv-alt Any comments from you before we merge?

**Review by ldv-alt — CHANGES_REQUESTED** [review]
The change looks fine, but I'd prefer the commit message to be of the same style as other commit messages.

**Comment by crd477** [comment]
Whoops, sorry about that.  I hope I addressed it.

**Comment by solardiz** [comment]
@ldv-alt Good catch! I forgot to take a look at the full commit message.

**Review by ldv-alt — APPROVED** [review]

**Comment by solardiz** [comment]
I just noticed the indentation of case `CYGWIN_NT*` added here is wrong - it uses spaces instead of tabs, which the other cases use. Also, I think addition of Cygwin support is significant enough to mention in `CHANGES`, but we did not. Unfortunately, we've already tagged the release.

@ldv-alt Do you think we should proceed to release and announce 2.0.3 as-is, and fix this indentation post-2.0.3?

**Comment by ldv-alt** [comment]
I've already sent the release tag to Sisyphus, so yes, I think we should proceed with the release.

**Comment by solardiz** [comment]
> I've already sent the release tag to Sisyphus, so yes, I think we should proceed with the release.

OK, thanks. I'll proceed.

**Comment by solardiz** [comment]
> I just noticed the indentation of case `CYGWIN_NT*` added here is wrong - it uses spaces instead of tabs, which the other cases use. Also, I think addition of Cygwin support is significant enough to mention in `CHANGES`, but we did not.

I've just pushed 974ee6362d5a05513a227ffa2f0a6ed4b80cd1af fixing this, but it's post-2.0.3 now.

**Comment by solardiz** [comment]
The `ifndef` added here break compatibility with Solaris' native `make`. In practice, most Solaris systems also have `gmake` installed, and it still works, but it's not ideal that we made a change that breaks something that previously worked. Any ideas for keeping this portable?

**Comment by solardiz** [comment]
> The `ifndef` added here break compatibility with Solaris' native `make`.

Fixed in #32. The fix also works with AIX' native make and shell (but there are other issues on AIX, unrelated to these changes).

**Pull request merged**
