### PR TITLE
Remove non-existent symbols to fix -Wl,--no-undefined-version

### PR DESCRIPTION
**Pull request by MaskRay**

### CODE REVIEW

**Comment by MaskRay** [comment]
See https://maskray.me/blog/2020-11-15-explain-gnu-linker-options#no-undefined-version

**Review by ldv-alt — APPROVED** [review]
Looks good.

**Comment by ldv-alt** [comment]
I'd love to see the result of our CI tests, though.
@solardiz Apparently, I have no permissions to approve running workflows for this PR.

**Comment by solardiz** [comment]
> I'd love to see the result of our CI tests, though.
> @solardiz Apparently, I have no permissions to approve running workflows for this PR.

@ldv-alt I've just approved that, and all checks have passed. I've also added you as a maintainer. Please feel free to merge this PR. Thanks!

**Pull request merged**
